# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/jirom-1/cs-848-visualization-project
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "argocd-test"

# imagePullSecrets: ["regcred"]

service:
  type: ClusterIP
  port: 80
  targetPort: 5006




